### ISSUE TITLE
BUG: nats-utility incompatible with TMS API path updates

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/nats-utilities#33]
Since the TMS API has been updated to version the API and rationalise the endpoints (ref: https://github.com/frmscoe/tms-service/issues/128), the nats-utility generates an error when sending a message into the TMS API via its new restPublish service:
```
2024-06-22 18:07:52 {
2024-06-22 18:07:52   message: 'nats communication was triggered',
2024-06-22 18:07:52   serviceOperation: undefined,
2024-06-22 18:07:52   id: undefined
2024-06-22 18:07:52 }
2024-06-22 18:07:52 {
2024-06-22 18:07:52   message: 'Subscription to event-director was done',
2024-06-22 18:07:52   serviceOperation: undefined,
2024-06-22 18:07:52   id: undefined
2024-06-22 18:07:52 }
2024-06-22 18:07:52 {
2024-06-22 18:07:52   message: AxiosError: connect ECONNREFUSED 127.0.0.1:5000
2024-06-22 18:07:52       at AxiosError.from (/home/app/node_modules/axios/dist/node/axios.cjs:841:14)
2024-06-22 18:07:52       at RedirectableRequest.handleRequestError (/home/app/node_modules/axios/dist/node/axios.cjs:3106:25)
2024-06-22 18:07:52       at RedirectableRequest.emit (node:events:519:28)
2024-06-22 18:07:52       at eventHandlers.<computed> (/home/app/node_modules/follow-redirects/index.js:38:24)
2024-06-22 18:07:52       at ClientRequest.emit (node:events:519:28)
2024-06-22 18:07:52       at Socket.socketErrorListener (node:_http_client:500:9)
2024-06-22 18:07:52       at Socket.emit (node:events:519:28)
2024-06-22 18:07:52       at emitErrorNT (node:internal/streams/destroy:169:8)
2024-06-22 18:07:52       at emitErrorCloseNT (node:internal/streams/destroy:128:3)
2024-06-22 18:07:52       at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-06-22 18:07:52       at Axios.request (/home/app/node_modules/axios/dist/node/axios.cjs:4224:41)
2024-06-22 18:07:52       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-22 18:07:52       at async tms (/home/app/build/app.controller.js:39:36)
2024-06-22 18:07:52       at async /home/app/build/app.js:30:13
2024-06-22 18:07:52       at async /home/app/build/app.js:21:13
2024-06-22 18:07:52       at async bodyParser (/home/app/node_modules/koa-bodyparser/index.js:78:5) {
2024-06-22 18:07:52     port: 5000,
2024-06-22 18:07:52     address: '127.0.0.1',
2024-06-22 18:07:52     syscall: 'connect',
2024-06-22 18:07:52     code: 'ECONNREFUSED',
2024-06-22 18:07:52     errno: -111,
2024-06-22 18:07:52     config: {
2024-06-22 18:07:52       transitional: [Object],
2024-06-22 18:07:52       adapter: [Array],
2024-06-22 18:07:52       transformRequest: [Array],
2024-06-22 18:07:52       transformResponse: [Array],
2024-06-22 18:07:52       timeout: 0,
2024-06-22 18:07:52       xsrfCookieName: 'XSRF-TOKEN',
2024-06-22 18:07:52       xsrfHeaderName: 'X-XSRF-TOKEN',
2024-06-22 18:07:52       maxContentLength: -1,
2024-06-22 18:07:52       maxBodyLength: -1,
2024-06-22 18:07:52       env: [Object],
2024-06-22 18:07:52       validateStatus: [Function: validateStatus],
2024-06-22 18:07:52       headers: [Object [AxiosHeaders]],
2024-06-22 18:07:52       method: 'post',
2024-06-22 18:07:52       url: 'http://localhost:5000/v1/evaluate/iso20022/pacs.008.001.10',
2024-06-22 18:07:52       data: '{"TxTp":"pacs.008.001.10","FIToFICstmrCdt":{"GrpHdr":{"MsgId":"43c741642a8643f68e8c453adc9dd555","CreDtTm":"2024-06-22T16:02:51.962Z","NbOfTxs":1,"SttlmInf":{"SttlmMtd":"CLRG"}},"CdtTrfTxInf":{"PmtId":{"InstrId":"5ab4fc7355de4ef8a75b78b00a681ed2","EndToEndId":"4d7a5e9303d041e9884f71f474c1ed90"},"IntrBkSttlmAmt":{"Amt":{"Amt":367.06,"Ccy":"XTS"}},"InstdAmt":{"Amt":{"Amt":367.06,"Ccy":"XTS"}},"ChrgBr":"DEBT","ChrgsInf":{"Amt":{"Amt":0,"Ccy":"XTS"},"Agt":{"FinInstnId":{"ClrSysMmbId":{"MmbId":"dfsp001"}}}},"InitgPty":{"Nm":"April Blake Grant","Id":{"PrvtId":{"DtAndPlcOfBirth":{"BirthDt":"1968-02-01","CityOfBirth":"Unknown","CtryOfBirth":"ZZ"},"Othr":{"Id":"+27730975224","SchmeNm":{"Prtry":"MSISDN"}}}},"CtctDtls":{"MobNb":"+27-730975224"}},"Dbtr":{"Nm":"April Blake Grant","Id":{"PrvtId":{"DtAndPlcOfBirth":{"BirthDt":"1999-06-04","CityOfBirth":"Unknown","CtryOfBirth":"ZZ"},"Othr":{"Id":"43f3271663a44a3288f799dc04c5f6bf","SchmeNm":{"Prtry":"TAZAMA_EID"}}}},"CtctDtls":{"MobNb":"+27-730975224"}},"DbtrAcct":{"Id":{"Othr":{"Id":"d86d5ffdaf5241ddbc18130cd18fdd03","SchmeNm":{"Prtry":"MSISDN"}}},"Nm":"April Grant"},"DbtrAgt":{"FinInstnId":{"ClrSysMmbId":{"MmbId":"dfsp001"}}},"CdtrAgt":{"FinInstnId":{"ClrSysMmbId":{"MmbId":"dfsp002"}}},"Cdtr":{"Nm":"Felicia Easton Quill","Id":{"PrvtId":{"DtAndPlcOfBirth":{"BirthDt":"1935-05-08","CityOfBirth":"Unknown","CtryOfBirth":"ZZ"},"Othr":{"Id":"8deea324fd2e4deca16b21979a6a2c97","SchmeNm":{"Prtry":"TAZAMA_EID"}}}},"CtctDtls":{"MobNb":"+27-707650428"}},"CdtrAcct":{"Id":{"Othr":{"Id":"d0f7265b70ad4f4f90ed18c519f1292b","SchmeNm":{"Prtry":"MSISDN"}}},"Nm":"Felicia Quill"},"Purp":{"Cd":"MP2P"}},"RgltryRptg":{"Dtls":{"Tp":"BALANCE OF PAYMENTS","Cd":"100"}},"RmtInf":{"Ustrd":"Generic payment description"},"SplmtryData":{"Envlp":{"Doc":{"Xprtn":"2021-11-30T10:38:56.000Z","InitgPty":{"Glctn":{"Lat":"-3.1609","Long":"38.3588"}}}}}}}'
2024-06-22 18:07:52     },
2024-06-22 18:07:52     request: Writable {
2024-06-22 18:07:52       _events: [Object],
2024-06-22 18:07:52       _writableState: [WritableState],
2024-06-22 18:07:52       _maxListeners: undefined,
2024-06-22 18:07:52       _options: [Object],
2024-06-22 18:07:52       _ended: false,
2024-06-22 18:07:52       _ending: true,
2024-06-22 18:07:52       _redirectCount: 0,
2024-06-22 18:07:52       _redirects: [],
2024-06-22 18:07:52       _requestBodyLength: 1879,
2024-06-22 18:07:52       _requestBodyBuffers: [Array],
2024-06-22 18:07:52       _eventsCount: 3,
2024-06-22 18:07:52       _onNativeResponse: [Function (anonymous)],
2024-06-22 18:07:52       _currentRequest: [ClientRequest],
2024-06-22 18:07:52       _currentUrl: 'http://localhost:5000/v1/evaluate/iso20022/pacs.008.001.10',
2024-06-22 18:07:52       [Symbol(shapeMode)]: true,
2024-06-22 18:07:52       [Symbol(kCapture)]: false
2024-06-22 18:07:52     },
2024-06-22 18:07:52     cause: Error: connect ECONNREFUSED 127.0.0.1:5000
2024-06-22 18:07:52         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
2024-06-22 18:07:52       errno: -111,
2024-06-22 18:07:52       code: 'ECONNREFUSED',
2024-06-22 18:07:52       syscall: 'connect',
2024-06-22 18:07:52       address: '127.0.0.1',
2024-06-22 18:07:52       port: 5000
2024-06-22 18:07:52     }
2024-06-22 18:07:52   },
2024-06-22 18:07:52   serviceOperation: undefined,
2024-06-22 18:07:52   id: undefined
2024-06-22 18:07:52 }
2024-06-22 18:07:52 {
2024-06-22 18:07:52   message: 'POST /restPublish - 4ms',
2024-06-22 18:07:52   serviceOperation: undefined,
2024-06-22 18:07:52   id: undefined
2024-06-22 18:07:52 }
```

I can send a request normally to the same API URI successfully, no issues. It just won't work via the restPublish.

If I copy-paste the URL string http://localhost:5000/v1/evaluate/iso20022/pacs.008.001.10 from the body of the restPublish request, it works fine, so I'm pretty sure the URI is correct.

The nats utility is working fine for non-TMS API loops

**Comment by cshezi** [comment]
Pacs002
![Image](https://github.com/frmscoe/nats-utilities/assets/131665740/6b58c179-50d7-4736-bb6f-2494dc439374)

Pacs008
![Image](https://github.com/frmscoe/nats-utilities/assets/131665740/94761918-fdfa-4f7b-a8af-5f0eae0a93b5)



**No bug was found please ensure that nats-utilities and tms are running on different ports
